import {
    idAbBuyPrice,
    idAbSellPrice,
    idAbMaxPurchases,
    idAbRandMinBidInput,
    idAbRandMinBuyInput,
    idAbRandMinBuyToggle,
    idAbRandMinBidToggle,
    
    
    idFilterDropdown,
    idSelectedFilter,
    idAbCardCount,
    idAbMaxBid,
    idAbItemExpiring,
    idAbBidExact,
    idAbMinDeleteCount,
    idAbSellToggle,
    idAbWaitTime,
    idAbCycleAmount,
    idAbPauseFor,
    idAbStopAfter,
    idAbMinRating,
    idAbMaxRating,
    idAbAddBuyDelay,
    idAbDelayToAdd,
    idAbAddFilterGK,
    idAbCloseTabToggle,
    idAbMessageNotificationToggle,
    idAbSoundToggle,
    idTelegramBotToken,
    idTelegramChatId,
    idNotificationType,
    idDiscordToken,
    idDiscordChannelId,
    idProgressAutobuyer,
    idAutoBuyerFoundLog,
    idSearchCancelButton,
    idInfoWrapper,
    idPreserveChanges,
    idClearLogButton,
    idCalcBinPrice,
    idTestNotification,
    idSelectFilterCount,
    idDeleteFilter,
    idAbSolveCaptcha,
    idSellAfterTax,
    idAbSearchProgress,
    idAbStatisticsProgress,
    idAbRequestCount,
    idAbCoins,
    idAbProfit,
    idAbSearchedItems,
    idAbStatus,
    idAbSoldItems,
    idAbUnsoldItems,
    idAbAvailableItems,
    idAbActiveTransfers,
    idAbNumberFilterSearch,
    idAbStopErrorCode,
    idAbStopErrorCodeCount,
    idSearchWrapper,
    idWinMp3,
    idFinishMp3,
    idCapatchaMp3,
    idProxyAddress,
    idProxyPort,
    idProxyLogin,
    idAntiCaptchKey,
    idProxyPassword,
    idAutoClearLog,
    idSellRatingThreshold,
    idSellFutBinPrice,
    idSellFutBinPercent,
    idAbCompactView,
    } from "./elementIds.constants";
    
    
    export const injectFMT = () => {
        $(document).getElementById(idAbBuyPrice).value = 1000;
      $(document).getElementById(idAbSellPrice).value = 1000;
      
    };
    
    
    